### ISSUE TITLE
Feedback from your friend

### ISSUE THREAD

**Issue by mfehrenbach** [typography-interaction-2425/manuscript#1]
- [x] Do this first!

- Put your reset in! 
- https://github.com/typography-interaction-2425/manuscript/blob/bbe911479126ecd90170f82afa4d6b5554abdc1b/index.html#L11
- asdas
- asd
- You got this!

✊

**Comment by rijkvanzanten** [comment]
![](https://i.giphy.com/media/v1.Y2lkPTc5MGI3NjExdm1qdzh3bTI5MjM1cXI4enlyOWZzdzNjYjQxeHkybXl2NXV0eW1rZiZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/osjgQPWRx3cac/giphy.gif)

**Comment by rijkvanzanten** [comment]
OK I'm done. Thanks!
